# Generated by Django 4.1.3 on 2023-01-11 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook2_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='friend_requests',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='facebook2_app.person'),
            preserve_default=False,
        ),
    ]
