# Generated by Django 4.1.3 on 2023-01-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook2_app', '0002_person_friend_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='friend_requests',
        ),
    ]
