# Generated by Django 4.1.3 on 2023-01-18 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facebook2_app', '0005_remove_post_likes_likeprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField()),
                ('author', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook2_app.post')),
            ],
        ),
        migrations.AddField(
            model_name='likeprofile',
            name='liked_comments',
            field=models.ManyToManyField(to='facebook2_app.comment'),
        ),
    ]
