# Generated by Django 4.1.3 on 2023-01-19 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook2_app', '0006_comment_likeprofile_liked_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeprofile',
            name='liked_comments',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
