# Generated by Django 4.1.3 on 2023-01-19 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook2_app', '0008_comment_likeprofile_liked_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook2_app.person'),
        ),
    ]
