# Generated by Django 4.1.3 on 2023-01-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook2_app', '0010_profilepicture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilePicture',
        ),
    ]
