# Generated by Django 4.1.3 on 2023-01-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook2_app', '0012_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='notifications',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
