# Generated by Django 4.1.3 on 2023-01-24 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook2_app', '0013_person_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='notifications',
        ),
    ]
