# Generated by Django 4.1.3 on 2023-01-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces_app', '0002_person_unread'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='post_vis',
            field=models.PositiveIntegerField(choices=[('0', 'Friends'), ('1', "Friends' friends"), ('2', 'Everyone')], default='0'),
        ),
    ]
