# Generated by Django 4.1.3 on 2023-02-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces_app', '0003_person_post_vis'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bio',
            field=models.TextField(default='', max_length=300),
        ),
    ]
