# Generated by Django 4.1.3 on 2023-02-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces_app', '0004_person_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(default='', max_length=512),
        ),
    ]
